### ISSUE TITLE
Moving BTODataTools@ee.doe.gov email addresses over to shared mailing list (groups.io)

### ISSUE THREAD

**Issue by laurenliz22** [BuildingSync/project-tracker#103]
Hi All! 
As part of the DOE Data Tools projects (SEED, BuildingSync, Audit Template, etc), we have a website that was developed by Katherine at https://buildingdata.energy.gov/. (The source code is here for reference: https://github.com/BuildingEnergyTools/tools-website). If you look at the website under the respective data tool links there is an email for BTODataTools@ee.doe.gov. We have for a long time been planning on moving those email addresses over to a shared mailing list

We purchased a subscription to groups.io and have set up a few lists already. However, we need to finish all of the setup and make sure it will meet our needs. Hannah, is this something you can lead and figure out under the BSync task? Here is where the details get fuzzy, sorry! The requirements at the moment are the following:

- Right now the domain for the mailing list is buildingenergytools.org (so buildingsync@lists.buildingenergytools.org). Are we able to host this as buildingsync@lists.buildingdata.energy.gov? Reach out to NREL's Damon Haley perhaps to start with.
- Can groups.io be setup to have a list that only emails the admins? This list/email would be used on a webform to submit "help" or "i'm interested style" requests.
- Can groups.io have a moderate all messages function on a mailing list?
- Update the buildingdata.energy.gov website to add a contact webform. Add a new card on the bottom of the main page for the link. DOE likes this webform https://www.energycodes.gov/technical-assistance/help-desk. (Katherine -- do you want to take this task on?)

I will add you all to be admins on the groups.io website so you can mess around and figure out how to make this work right. Harry and Jeff will have the ultimate say in all of this, we just need to figure out what groups.io can do first so that we can inform them.

**Comment by haneslinger** [comment]
https://github.com/BuildingEnergyTools/tools-website/tree/Create-help-desk
