### ISSUE TITLE
groups.io: Task 4: Update the buildingdata.energy.gov website to add a contact webform

### ISSUE THREAD

**Issue by laurenliz22** [BuildingSync/project-tracker#111]
Update the buildingdata.energy.gov website to add a contact webform. Add a new card on the bottom of the main page for the link. DOE likes this webform https://www.energycodes.gov/technical-assistance/help-desk.

**Comment by haneslinger** [comment]
https://github.com/BuildingEnergyTools/tools-website/tree/Create-help-desk
