### ISSUE TITLE
groups.io: Task 3: Determine if groups.io can have a moderate all messages function on a mailing list

### ISSUE THREAD

**Issue by laurenliz22** [BuildingSync/project-tracker#112]

**Comment by haneslinger** [comment]
There are several references to moderation in the [groups.io owner manual,](https://groups.io/helpcenter/ownersmanual)  including [manual modding](https://groups.io/helpcenter/ownersmanual/1/customizing-group-settings/spam-control-and-moderation-settings), [content control](https://groups.io/helpcenter/ownersmanual/1/customizing-group-settings/message-formatting-settings), and [modding individuals](https://groups.io/helpcenter/ownersmanual/1/managing-members/moderating-individual-members). @laurenliz22 can we close?
