### ISSUE TITLE
groups.io: Task 1: Determine if can change domain for mailing list to .gov

### ISSUE THREAD

**Issue by laurenliz22** [BuildingSync/project-tracker#114]
Right now the domain for the mailing list is buildingenergytools.org (so buildingsync@lists.buildingenergytools.org). Are we able to host this as buildingsync@lists.buildingdata.energy.gov? Reach out to NREL's Damon Haley perhaps to start with.

**Comment by haneslinger** [comment]
Email sent!

**Comment by haneslinger** [comment]
We talked to Damon about it! He say we can probably use amazons tooling, but he will have to set up a bunch of stuff with us cause we can't touch the cloudfront stuff.

That would be in June/July. They say they are swamped and it's a 4-6 hour endevour.

**Comment by haneslinger** [comment]
We believe the answer to be no. @laurenliz22, can we close?
