### ISSUE TITLE
Review updates to publication and onboarding document and oxygenXML

### ISSUE THREAD

**Issue by isalanglois** [BuildingSync/project-tracker#142]

**Comment by JieXiong9119** [comment]
Onboarding doc: https://docs.google.com/document/d/1WLKz-Dq6Z5KPHvXTvVbaBhdEuLJj36Ce/edit?pli=1

**Comment by laurenliz22** [comment]
@laurenliz22 @nllong review onboarding document

**Comment by JieXiong9119** [comment]
Publications (Thanks to Nicholas!): 
1. https://www.osti.gov/biblio/1846197
2. https://www.osti.gov/biblio/1867076
3. https://www.tandfonline.com/doi/full/10.1080/23744731.2022.2133329

**Comment by laurenliz22** [comment]
Put a list of all XML editors and have users figure out what they'd need
- VS Code (free)

**Comment by laurenliz22** [comment]
https://buildingsync.net/references for publications

**Comment by axelstudios** [comment]
PR for publication updates: https://github.com/BuildingSync/BuildingSync-website/pull/173
