### ISSUE TITLE
[8/31/2023] WCMs

### ISSUE THREAD

**Issue by laurenliz22** [BuildingSync/project-tracker#165]

**Comment by JieXiong9119** [comment]
Update shared sheet with final decision column: 
https://docs.google.com/spreadsheets/d/15GUAZ6koG7dWHk_P00Gi-j43kdJReL7C/edit?pli=1#gid=302699535
* Add "not WCM but potential ECM" measures
* Disregard O&M measures

**Comment by JieXiong9119** [comment]
Implementation PRs
https://github.com/BuildingSync/schema/pull/480
https://github.com/BuildingSync/schema/pull/481
