### ISSUE TITLE
Create a diagram on where the main files live and how the data flow between repositories.

### ISSUE THREAD

**Issue by nllong** [BuildingSync/project-tracker#30]
Ted to schedule a meeting to agree on what will be reorged.

**Comment by macintoshpie** [comment]
- website
    - see #31 
- selection-tool
    - selectiontool.buildingsync.net
    - pulls use cases and their passing files from new use-cases repo
    - add documentation about schematron, use cases, api, etc to the site itself (move out of readmes in repo?)
    - consider "rebranding" to a more generic 'buildingsync web tools' site?
- schema
    - documentation is light here, should be mostly in docs repo
    - all schema stuff like XSD
    - [DELETE] can we get rid of current translator directory? what does it do?
    - [DELETE] examples
    - [NEW] translation
        - list of directories of "x.x.x to y.y.y" which contain a readme and xslt for making the transformation
            - some might have to include a python script or something as well, e.g. we changed IDs to be required and IDK how to do that in xslt??
- testsuite
    - repo for python schematron validation and generation tool
    - keep only the python tool and get rid of the schematron files
- [NEW] use-cases 
    - repository of use cases (schematron files), examples of valid files, and tests for them if so desired
    - bsync users make PRs to add their own
    - we pull right from this repo to update selection-tool
    - find a way to specify what bsync versions a schematron supports
- docs
    - static site at docs.buildingsync.net (read the docs style)
    - should provide technical documentation and examples for the schema (users should go to repos to see specific tool docs)
    - Should function like [https://docs.brickschema.org/intro.html](https://docs.brickschema.org/intro.html)
        - different sections
            - BuildingSync model
                - Relationships
            - XML Tools (schema validation, xml manipulation, etc)
            - etc
    - examples/guides
        - take from /schema/examples create directories where is an example with a readme explaining what it demonstrates and BuildingSync xml file, or have a README in the examples directory which explains what each file demonstrates
        - These could be used for the website's examples somehow
        - Do we want every example to be using the latest buildingsync version?
    - misc resources
    - jupyter notebooks
    - guides
        - onboarding guide

**Comment by macintoshpie** [comment]
Changes implemented:
- moved schematron files out of `testsuite` and into new repo `use-cases`. `testsuite` is now a standalone python package for validating schematron and doesn't manage schematron files
- we removed the `website` repo, `selection-tool` now covers all documentation and use case validation
- we removed the `examples` repo, and moved those jupyter notebooks into schema/docs/notebooks

**Comment by macintoshpie** [comment]
Changes implemented:
- moved schematron files out of testsuite and into new repo use-cases. testsuite is now a standalone python package for validating schematron and doesn't manage schematron files
- we removed the website repo, selection-tool now covers all documentation and use case validation
- we removed the examples repo, and moved those jupyter notebooks into schema/docs/notebooks
