### ISSUE TITLE
[3/19] redesign the layout of the selection tool page to integrate the main buildingsync.net site

### ISSUE THREAD

**Issue by nllong** [BuildingSync/project-tracker#31]
Initial idea is to take the BuidingSync selection tool's website and update the front page to become the main entrypoint to buildingsync. We would then move content from buildingsync.net into the "selection tool website", then eventually deprecate buildingsync.net's site and move selection tool to buildingsync.net. thoughts? @kflemin 

first action item is to create rough diagram of new buildingsync front page that is both flashy (with the animation from buildingsync.net?) and informative (with information similar to https://brickschema.org/get-started). 

* Need to determine tasks / owners / responsibilities / timeline!

**Comment by kflemin** [comment]
@nllong what is the timeline on this?

**Comment by nllong** [comment]
Let's plan on having a rough layout (mockups) by end of next week. is this something that you can spin marj up to do @kflemin ?

**Comment by macintoshpie** [comment]
@nllong @kflemin I sketched out some ideas for the site layout here:
https://docs.google.com/document/d/1_QYKO5zvX1GI1FrPtnN9wXIKx4G75wRva6FIwCjuQb8/edit?usp=sharing

Feel free to edit/comment

**Comment by kflemin** [comment]
that looks good @macintoshpie, thanks!

**Comment by macintoshpie** [comment]
More inspo: https://nemsis.org/
